### ISSUE TITLE
Chapter 5 issue

### ISSUE THREAD

**Issue by jhagege** [falloutdurham/beginners-pytorch-deep-learning#3]
'<' not supported between instances of 'Example' and 'Example' when running line:
train(epochs=5, model=model, optimizer=optimizer, criterion=criterion, train_iterator=train_iterator, valid_iterator=valid_iterator) (which by the way does not appear in the notebook).
Any idea how to fix ? 

Great, great book by the way :)

**Comment by falloutdurham** [comment]
Argh…I may not get to this until the weekend because of travel, but I'll sort it out! And thanks :)

**Comment by falloutdurham** [comment]
This is totally my fault - when transferring the code to the book, I somehow omitted the `sort_key` lambda when setting up the `BucketIterator` splits. Without the lambda, the training loop fails when it tries to get similar-sized batches, because it has nothing available to use for comparison (hence the error about `<`). I've pushed up a fix.
