### ISSUE TITLE
Ch 5 Error: OSError: [E050] Can't find model 'en'. 

### ISSUE THREAD

**Issue by CloudaYolla** [falloutdurham/beginners-pytorch-deep-learning#34]
Hi,

While executing the cell below:

```

LABEL = data.LabelField()
TWEET = data.Field(tokenize='spacy', lower=True)

fields = [('score',None), ('id',None),('date',None),('query',None),
      ('name',None),
      ('tweet', TWEET),('category',None),('label',LABEL)] 
```
I get the following error:

`OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
`

Thank you.

**Comment by dpapathanasiou** [comment]
After you install [spacy](https://spacy.io/), you also have to download the modules corresponding to the languages you're interested in (in this case, English).

As [described in the docs](https://spacy.io/usage/models#download), you need to do:

```sh
python -m spacy download en_core_web_sm
```

*after* you've done this (which seems like you have, since the `import spacy` command didn't trigger an error):

```sh
pip install spacy
```
