### ISSUE TITLE
Chapter 4 - Replacing the Classifier

### ISSUE THREAD

**Issue by ldkong1205** [falloutdurham/beginners-pytorch-deep-learning#35]
transfer_model.fc = nn.Sequential(nn.Linear(transfer_model.fc.in_features, 500),
                                  nn.ReLU(),
                                  nn.Dropout(),
                                  nn.Linear(500,2)) 

AttributeError: 'Sequential' object has no attribute 'in_features'

**Comment by MarcusFra** [comment]
Hmm, I cannot reproduce this error.
Did you run the https://github.com/falloutdurham/beginners-pytorch-deep-learning/blob/master/chapter4/Chapter%204.ipynb or did you copy the code from the book?
Maybe it's due to the defintion of `transfer_model` - did you run `transfer_model = models.resnet50(pretrained=True)` earlier?
After loading this pretrained model you can check the structure of the fc block by `print(transfer_model.fc)`. It should return `Linear(in_features=2048, out_features=1000, bias=True)`.

After redefining this with `transfer_model.fc = nn.Sequential(nn.Linear(transfer_model.fc.in_features, 500), ...))` you should get
```
Sequential(
  (0): Linear(in_features=2048, out_features=500, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.5, inplace=False)
  (3): Linear(in_features=500, out_features=2, bias=True)
```
when you run `print(transfer_model.fc)`.

**Comment by ldkong1205** [comment]
> Hmm, I cannot reproduce this error.
> Did you run the https://github.com/falloutdurham/beginners-pytorch-deep-learning/blob/master/chapter4/Chapter%204.ipynb or did you copy the code from the book?
> Maybe it's due to the defintion of `transfer_model` - did you run `transfer_model = models.resnet50(pretrained=True)` earlier?
> After loading this pretrained model you can check the structure of the fc block by `print(transfer_model.fc)`. It should return `Linear(in_features=2048, out_features=1000, bias=True)`.
> 
> After redefining this with `transfer_model.fc = nn.Sequential(nn.Linear(transfer_model.fc.in_features, 500), ...))` you should get
> 
> ```
> Sequential(
>   (0): Linear(in_features=2048, out_features=500, bias=True)
>   (1): ReLU()
>   (2): Dropout(p=0.5, inplace=False)
>   (3): Linear(in_features=500, out_features=2, bias=True)
> ```
> 
> when you run `print(transfer_model.fc)`.

Thank you for your reply. 😁
