### ISSUE TITLE
Chapter 3 - Making Predictions Method from Chapter 2 does not work

### ISSUE THREAD

**Issue by Mahosaurus** [falloutdurham/beginners-pytorch-deep-learning#78]
Replacing the model from Chapter 2 with the one of Chapter 3, results in the following message when the prediction algorithm is called:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (256x36 and 9216x4096)
EDIT: Found solution, using .unsqueeze(0)

**Comment by MarcusFra** [comment]
Hi @Mahosaurus!
Could you please elaborate a bit more what issue has arisen? 
Did you need to replace the model in order to run the code?
Have you replaced the code line
````
img = torch.unsqueeze(img, 0)
```` 
in https://github.com/falloutdurham/beginners-pytorch-deep-learning/blob/master/chapter2/Chapter%202.ipynb?

If you still have the stacktrace I'd be thankful if you can share it.

**Comment by MarcusFra** [comment]
Ah, sorry my fault. You were referring to chapter 3. World you like to share your whole notebook with your solution?

**Comment by Mahosaurus** [comment]
Hi @MarcusFra: Thanks for responding. I cant share the notebook as I have been using it for further experimentation.
The prediction part for chapter 3, I changed as follows in comp to chapter 2.
```labels = ['cat','fish']

img = Image.open("file.jpg") 
img = img_transforms(img).unsqueeze(0)

prediction = F.softmax(alexcnnmodel(img))
prediction = prediction.argmax()

labels[prediction]

**Comment by Mahosaurus** [comment]
@MarcusFra : My mistake was to look into the old repository and mix the code up. This one here has the correct syntax.
